import { createReadStream, type PathLike } from 'node:fs';

export const readFirstNBytes = async (path: PathLike, n: number = 1 * 1024 * 1024): Promise<Buffer> => {
  const chunks: Buffer[] = [];
  for await (const chunk of createReadStream(path, { start: 0, end: n - 1 })) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks);
};

export const ASSET_DATA = {
  url: 'https://bitmovin.com/demos/drm',
  dir: './test/assets/segments',
  inputPath: './test/assets/bitmovin.enc.mp4',
  outputPath: './test/assets/bitmovin.dec.mp4',
  keyId: 'eb676abbcb345e96bbcf616630f1a3da',
  keyValue: '100b6c20940f779a4589152b57d2dacb',
  keyPair: 'eb676abbcb345e96bbcf616630f1a3da:100b6c20940f779a4589152b57d2dacb',
  pssh: {
    playready:
      'AAADInBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAwICAwAAAQABAPgCPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgB1ADIAcABuADYAegBUAEwAbABsADYANwB6ADIARgBtAE0AUABHAGoAMgBnAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AE4ANABRAHkAYwBZAE4AegBOAHgAWQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAGQAaQByAGUAYwB0AHQAYQBwAHMALgBuAGUAdAAvAHAAcgAvAHMAdgBjAC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPwBQAGwAYQB5AFIAaQBnAGgAdAA9ADEAJgBhAG0AcAA7AEMAbwBuAHQAZQBuAHQASwBlAHkAPQBFAEEAdABzAEkASgBRAFAAZAA1AHAARgBpAFIAVQByAFYAOQBMAGEAeQB3AD0APQA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==',
    widevine:
      'AAAAW3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADsIARIQ62dqu8s0Xpa7z2FmMPGj2hoNd2lkZXZpbmVfdGVzdCIQZmtqM2xqYVNkZmFsa3IzaioCSEQyAA==',
  },
};
